//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.09 at 02:43:25 AM CEST 
//


package m3objects;

import jade.core.AID;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anAnnounce" type="{http://www.openM3.org/m3}Announce" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anAnnounce"
})
@XmlRootElement(name = "Announces")
public class Announces implements java.io.Serializable{

    @XmlElement(required = true)
    protected List<Announce> anAnnounce;

    /**
     * Gets the value of the anAnnounce property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anAnnounce property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnAnnounce().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Announce }
     * 
     * 
     */
    public List<Announce> getAnAnnounce() {
    	//System.out.println(anAnnounceToString());
        if (anAnnounce == null) {
            anAnnounce = new ArrayList<Announce>();
        }
        return this.anAnnounce;
    }
    private String anAnnounceToString()
    {
    	String rv = "";
    	if (anAnnounce == null) rv = "null";
    	else
    	{
    		for (int i = 0; i < anAnnounce.size(); i++)
    		{
    			rv += (anAnnounce.get(i).getAgentId()) + ", ";
    		}
    	}
    	
    	return rv;
    }
    
    
    public boolean removeAnnounce(String agentId)
    {
    	//System.out.println("Szukamy agenta " + agentId + "...");
    	//System.out.println(anAnnounceToString());
    	Integer d = null;
    	for(int i = 0; i < anAnnounce.size(); i++)
    	{
    		//System.out.println(anAnnounce.get(i).getAgentId());
    		if (anAnnounce.get(i).getAgentId().compareTo(agentId) == 0)
    		{
    			//System.out.println("Found !!! : " + anAnnounce.get(i).getAgentId());
    			d = i;
    		}
    	}
    	if (d != null) 
    	{
    		anAnnounce.remove(anAnnounce.get(d));
    	}
    	//System.out.println(anAnnounceToString());
    	return d != null;
    }

}
