//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.08 at 11:59:46 PM CEST 
//


package m3objects;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for Commodity_complexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Commodity_complexType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openM3.org/m3}GenericItem_complexType">
 *       &lt;sequence>
 *         &lt;element name="VirtualCommodity" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="groupingCost" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="availableAt">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="CalendarScheduledCommodity">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="IndependentlyScheduledCommodity">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="deliveryStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                   &lt;attribute name="deliveryCompletionTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="minBalance" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="maxBalance" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="activationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="expirationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="buyPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Commodity_complexType", propOrder = {
    "virtualCommodity",
    "availableAt",
    "calendarScheduledCommodity",
    "independentlyScheduledCommodity"
})
public class CommodityComplexType
    extends GenericItemComplexType
{

    @XmlElement(name = "VirtualCommodity")
    protected CommodityComplexType.VirtualCommodity virtualCommodity;
    @XmlElement(required = true)
    protected CommodityComplexType.AvailableAt availableAt;
    @XmlElement(name = "CalendarScheduledCommodity")
    protected CommodityComplexType.CalendarScheduledCommodity calendarScheduledCommodity;
    @XmlElement(name = "IndependentlyScheduledCommodity")
    protected CommodityComplexType.IndependentlyScheduledCommodity independentlyScheduledCommodity;
    @XmlAttribute
    protected Double minBalance;
    @XmlAttribute
    protected Double maxBalance;
    @XmlAttribute
    protected XMLGregorianCalendar activationTime;
    @XmlAttribute
    protected XMLGregorianCalendar expirationTime;
    @XmlAttribute
    protected BigDecimal sellPrice;
    @XmlAttribute
    protected BigDecimal buyPrice;

    /**
     * Gets the value of the virtualCommodity property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityComplexType.VirtualCommodity }
     *     
     */
    public CommodityComplexType.VirtualCommodity getVirtualCommodity() {
        return virtualCommodity;
    }

    /**
     * Sets the value of the virtualCommodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityComplexType.VirtualCommodity }
     *     
     */
    public void setVirtualCommodity(CommodityComplexType.VirtualCommodity value) {
        this.virtualCommodity = value;
    }

    /**
     * Gets the value of the availableAt property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityComplexType.AvailableAt }
     *     
     */
    public CommodityComplexType.AvailableAt getAvailableAt() {
        return availableAt;
    }

    /**
     * Sets the value of the availableAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityComplexType.AvailableAt }
     *     
     */
    public void setAvailableAt(CommodityComplexType.AvailableAt value) {
        this.availableAt = value;
    }

    /**
     * Gets the value of the calendarScheduledCommodity property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityComplexType.CalendarScheduledCommodity }
     *     
     */
    public CommodityComplexType.CalendarScheduledCommodity getCalendarScheduledCommodity() {
        return calendarScheduledCommodity;
    }

    /**
     * Sets the value of the calendarScheduledCommodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityComplexType.CalendarScheduledCommodity }
     *     
     */
    public void setCalendarScheduledCommodity(CommodityComplexType.CalendarScheduledCommodity value) {
        this.calendarScheduledCommodity = value;
    }

    /**
     * Gets the value of the independentlyScheduledCommodity property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityComplexType.IndependentlyScheduledCommodity }
     *     
     */
    public CommodityComplexType.IndependentlyScheduledCommodity getIndependentlyScheduledCommodity() {
        return independentlyScheduledCommodity;
    }

    /**
     * Sets the value of the independentlyScheduledCommodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityComplexType.IndependentlyScheduledCommodity }
     *     
     */
    public void setIndependentlyScheduledCommodity(CommodityComplexType.IndependentlyScheduledCommodity value) {
        this.independentlyScheduledCommodity = value;
    }

    /**
     * Gets the value of the minBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinBalance() {
        return minBalance;
    }

    /**
     * Sets the value of the minBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinBalance(Double value) {
        this.minBalance = value;
    }

    /**
     * Gets the value of the maxBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxBalance() {
        return maxBalance;
    }

    /**
     * Sets the value of the maxBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxBalance(Double value) {
        this.maxBalance = value;
    }

    /**
     * Gets the value of the activationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActivationTime() {
        return activationTime;
    }

    /**
     * Sets the value of the activationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivationTime(XMLGregorianCalendar value) {
        this.activationTime = value;
    }

    /**
     * Gets the value of the expirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationTime(XMLGregorianCalendar value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the sellPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * Sets the value of the sellPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSellPrice(BigDecimal value) {
        this.sellPrice = value;
    }

    /**
     * Gets the value of the buyPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * Sets the value of the buyPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBuyPrice(BigDecimal value) {
        this.buyPrice = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AvailableAt {

        @XmlAttribute(required = true)
        protected QName ref;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setRef(QName value) {
            this.ref = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CalendarScheduledCommodity {

        @XmlAttribute(required = true)
        protected QName ref;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setRef(QName value) {
            this.ref = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="deliveryStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="deliveryCompletionTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IndependentlyScheduledCommodity {

        @XmlAttribute(required = true)
        protected XMLGregorianCalendar deliveryStartTime;
        @XmlAttribute(required = true)
        protected XMLGregorianCalendar deliveryCompletionTime;

        /**
         * Gets the value of the deliveryStartTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDeliveryStartTime() {
            return deliveryStartTime;
        }

        /**
         * Sets the value of the deliveryStartTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDeliveryStartTime(XMLGregorianCalendar value) {
            this.deliveryStartTime = value;
        }

        /**
         * Gets the value of the deliveryCompletionTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDeliveryCompletionTime() {
            return deliveryCompletionTime;
        }

        /**
         * Sets the value of the deliveryCompletionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDeliveryCompletionTime(XMLGregorianCalendar value) {
            this.deliveryCompletionTime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="groupingCost" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class VirtualCommodity {

        @XmlAttribute
        protected BigDecimal groupingCost;

        /**
         * Gets the value of the groupingCost property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getGroupingCost() {
            return groupingCost;
        }

        /**
         * Sets the value of the groupingCost property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setGroupingCost(BigDecimal value) {
            this.groupingCost = value;
        }

    }

}
