//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.07 at 09:49:40 PM CEST 
//


package m3objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarketEntity" type="{http://www.openM3.org/m3}MarketEntity_complexType" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.openM3.org/m3}marketEntityKinds" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "marketEntity",
    "marketEntityKinds"
})
@XmlRootElement(name = "marketEntities")
public class MarketEntities {

    @XmlElement(name = "MarketEntity", required = true)
    protected List<MarketEntityComplexType> marketEntity;
    protected MarketEntityKinds marketEntityKinds;

    /**
     * Gets the value of the marketEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marketEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarketEntityComplexType }
     * 
     * 
     */
    public List<MarketEntityComplexType> getMarketEntity() {
        if (marketEntity == null) {
            marketEntity = new ArrayList<MarketEntityComplexType>();
        }
        return this.marketEntity;
    }

    /**
     * Gets the value of the marketEntityKinds property.
     * 
     * @return
     *     possible object is
     *     {@link MarketEntityKinds }
     *     
     */
    public MarketEntityKinds getMarketEntityKinds() {
        return marketEntityKinds;
    }

    /**
     * Sets the value of the marketEntityKinds property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketEntityKinds }
     *     
     */
    public void setMarketEntityKinds(MarketEntityKinds value) {
        this.marketEntityKinds = value;
    }

}
