//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.08 at 11:59:46 PM CEST 
//


package m3objects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the m3objects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: m3objects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommodityComplexType.AvailableAt }
     * 
     */
    public CommodityComplexType.AvailableAt createCommodityComplexTypeAvailableAt() {
        return new CommodityComplexType.AvailableAt();
    }

    /**
     * Create an instance of {@link CommodityKind }
     * 
     */
    public CommodityKind createCommodityKind() {
        return new CommodityKind();
    }

    /**
     * Create an instance of {@link Commodities }
     * 
     */
    public Commodities createCommodities() {
        return new Commodities();
    }

    /**
     * Create an instance of {@link CalendarPeriodComplexType.Aggregates }
     * 
     */
    public CalendarPeriodComplexType.Aggregates createCalendarPeriodComplexTypeAggregates() {
        return new CalendarPeriodComplexType.Aggregates();
    }

    /**
     * Create an instance of {@link Announces }
     * 
     */
    public Announces createAnnounces() {
        return new Announces();
    }

    /**
     * Create an instance of {@link GenericItemComplexType }
     * 
     */
    public GenericItemComplexType createGenericItemComplexType() {
        return new GenericItemComplexType();
    }

    /**
     * Create an instance of {@link CalendarPeriodComplexType }
     * 
     */
    public CalendarPeriodComplexType createCalendarPeriodComplexType() {
        return new CalendarPeriodComplexType();
    }

    /**
     * Create an instance of {@link CommodityComplexType }
     * 
     */
    public CommodityComplexType createCommodityComplexType() {
        return new CommodityComplexType();
    }

    /**
     * Create an instance of {@link CommodityComplexType.IndependentlyScheduledCommodity }
     * 
     */
    public CommodityComplexType.IndependentlyScheduledCommodity createCommodityComplexTypeIndependentlyScheduledCommodity() {
        return new CommodityComplexType.IndependentlyScheduledCommodity();
    }

    /**
     * Create an instance of {@link Announce }
     * 
     */
    public Announce createAnnounce() {
        return new Announce();
    }

    /**
     * Create an instance of {@link CommodityKinds }
     * 
     */
    public CommodityKinds createCommodityKinds() {
        return new CommodityKinds();
    }

    /**
     * Create an instance of {@link Market.TradedCommodity }
     * 
     */
    public Market.TradedCommodity createMarketTradedCommodity() {
        return new Market.TradedCommodity();
    }

    /**
     * Create an instance of {@link Market }
     * 
     */
    public Market createMarket() {
        return new Market();
    }

    /**
     * Create an instance of {@link KindDefinitionComplexType.TypeParameter }
     * 
     */
    public KindDefinitionComplexType.TypeParameter createKindDefinitionComplexTypeTypeParameter() {
        return new KindDefinitionComplexType.TypeParameter();
    }

    /**
     * Create an instance of {@link CommodityComplexType.CalendarScheduledCommodity }
     * 
     */
    public CommodityComplexType.CalendarScheduledCommodity createCommodityComplexTypeCalendarScheduledCommodity() {
        return new CommodityComplexType.CalendarScheduledCommodity();
    }

    /**
     * Create an instance of {@link KindDefinitionComplexType }
     * 
     */
    public KindDefinitionComplexType createKindDefinitionComplexType() {
        return new KindDefinitionComplexType();
    }

    /**
     * Create an instance of {@link Calendar }
     * 
     */
    public Calendar createCalendar() {
        return new Calendar();
    }

    /**
     * Create an instance of {@link Market.TradingPeriod }
     * 
     */
    public Market.TradingPeriod createMarketTradingPeriod() {
        return new Market.TradingPeriod();
    }

    /**
     * Create an instance of {@link ParameterDefinition }
     * 
     */
    public ParameterDefinition createParameterDefinition() {
        return new ParameterDefinition();
    }

    /**
     * Create an instance of {@link GenericItemComplexType.Parameter }
     * 
     */
    public GenericItemComplexType.Parameter createGenericItemComplexTypeParameter() {
        return new GenericItemComplexType.Parameter();
    }

    /**
     * Create an instance of {@link CommodityComplexType.VirtualCommodity }
     * 
     */
    public CommodityComplexType.VirtualCommodity createCommodityComplexTypeVirtualCommodity() {
        return new CommodityComplexType.VirtualCommodity();
    }

}
