//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.08 at 11:36:36 PM CEST 
//


package m3objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="Offer" type="{http://www.openM3.org/m3}Offer_complexType" maxOccurs="unbounded"/>
 *           &lt;element name="GroupingOffer" type="{http://www.openM3.org/m3}GroupingOffer_complexType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offerOrGroupingOffer"
})
@XmlRootElement(name = "Offers")
public class Offers {

    @XmlElements({
        @XmlElement(name = "GroupingOffer", type = GroupingOfferComplexType.class),
        @XmlElement(name = "Offer", type = OfferComplexType.class)
    })
    protected List<Object> offerOrGroupingOffer;

    /**
     * Gets the value of the offerOrGroupingOffer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerOrGroupingOffer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferOrGroupingOffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupingOfferComplexType }
     * {@link OfferComplexType }
     * 
     * 
     */
    public List<Object> getOfferOrGroupingOffer() {
        if (offerOrGroupingOffer == null) {
            offerOrGroupingOffer = new ArrayList<Object>();
        }
        return this.offerOrGroupingOffer;
    }

}
