//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.08 at 11:59:46 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openM3.org/m3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package m3objects;
