//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.07 at 09:49:53 PM CEST 
//


package m3objects;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for Programme_complexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Programme_complexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.openM3.org/m3}GenericDescription_group" minOccurs="0"/>
 *         &lt;element name="programmeCommodity">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="programmeMarketEntity">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.openM3.org/m3}GenericId_attributeGroup"/>
 *       &lt;attribute name="programmeType" use="required" type="{http://www.openM3.org/m3}DomainDefinedQName_simpleType" />
 *       &lt;attribute name="volume" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="associatedValue" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Programme_complexType", propOrder = {
    "name",
    "description",
    "programmeCommodity",
    "programmeMarketEntity"
})
public class ProgrammeComplexType {

    protected String name;
    protected String description;
    @XmlElement(required = true)
    protected ProgrammeComplexType.ProgrammeCommodity programmeCommodity;
    @XmlElement(required = true)
    protected ProgrammeComplexType.ProgrammeMarketEntity programmeMarketEntity;
    @XmlAttribute(required = true)
    protected QName programmeType;
    @XmlAttribute(required = true)
    protected double volume;
    @XmlAttribute
    protected BigDecimal associatedValue;
    @XmlAttribute(required = true)
    protected QName id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the programmeCommodity property.
     * 
     * @return
     *     possible object is
     *     {@link ProgrammeComplexType.ProgrammeCommodity }
     *     
     */
    public ProgrammeComplexType.ProgrammeCommodity getProgrammeCommodity() {
        return programmeCommodity;
    }

    /**
     * Sets the value of the programmeCommodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgrammeComplexType.ProgrammeCommodity }
     *     
     */
    public void setProgrammeCommodity(ProgrammeComplexType.ProgrammeCommodity value) {
        this.programmeCommodity = value;
    }

    /**
     * Gets the value of the programmeMarketEntity property.
     * 
     * @return
     *     possible object is
     *     {@link ProgrammeComplexType.ProgrammeMarketEntity }
     *     
     */
    public ProgrammeComplexType.ProgrammeMarketEntity getProgrammeMarketEntity() {
        return programmeMarketEntity;
    }

    /**
     * Sets the value of the programmeMarketEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgrammeComplexType.ProgrammeMarketEntity }
     *     
     */
    public void setProgrammeMarketEntity(ProgrammeComplexType.ProgrammeMarketEntity value) {
        this.programmeMarketEntity = value;
    }

    /**
     * Gets the value of the programmeType property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getProgrammeType() {
        return programmeType;
    }

    /**
     * Sets the value of the programmeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setProgrammeType(QName value) {
        this.programmeType = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     */
    public double getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     */
    public void setVolume(double value) {
        this.volume = value;
    }

    /**
     * Gets the value of the associatedValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAssociatedValue() {
        return associatedValue;
    }

    /**
     * Sets the value of the associatedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAssociatedValue(BigDecimal value) {
        this.associatedValue = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setId(QName value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ProgrammeCommodity {

        @XmlAttribute(required = true)
        protected QName ref;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setRef(QName value) {
            this.ref = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.openM3.org/m3}GenericRef_attributeGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ProgrammeMarketEntity {

        @XmlAttribute(required = true)
        protected QName ref;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setRef(QName value) {
            this.ref = value;
        }

    }

}
